# myhaki/lawyers/migrations/0001_initial.py
# Generated by Django 5.2.6 on 2025-09-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # Removed incorrect dependencies ('cases', '0001_initial'), ('users', '0001_initial')

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('lawyer', 'Lawyer'), ('lsk_admin', 'LSK Admin')], max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.JSONField(default=list)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['lawyer', 'lsk_admin']}, on_delete=django.db.models.deletion.CASCADE, to='lawyers.user')),
            ],
            options={
                'db_table': 'lawyer',
                'indexes': [
                    models.Index(fields=['practice_number'], name='lawyers_practic_123_idx'),
                    models.Index(fields=['latitude', 'longitude'], name='lawyers_latitud_456_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CPDPoint',
            fields=[
                ('cpd_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_earned', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers.lawyer')),
            ],
            options={
                'db_table': 'cpd_point',
                'indexes': [
                    models.Index(fields=['lawyer', 'case'], name='lawyers_lawyer_789_idx'),
                ],
            },
        ),
    ]